source 'https://github.com/CocoaPods/Specs.git'

target 'GiphyTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GIF support
  pod 'SwiftyGif'

end
